export const EventSourceType = {
  TOUCH_EVENT_FORM_DUMMY_NULL: 0,
  TOUCH_EVENT_FROM_GLASSES_R: 1,
  TOUCH_EVENT_FROM_RING: 2,
  TOUCH_EVENT_FROM_GLASSES_L: 3,
} as const;

export const EventSourceTypeName: Record<number, string> = {
  0: "TOUCH_EVENT_FORM_DUMMY_NULL",
  1: "TOUCH_EVENT_FROM_GLASSES_R",
  2: "TOUCH_EVENT_FROM_RING",
  3: "TOUCH_EVENT_FROM_GLASSES_L",
};

export const OsEventTypeList = {
  CLICK_EVENT: 0,
  SCROLL_TOP_EVENT: 1,
  SCROLL_BOTTOM_EVENT: 2,
  DOUBLE_CLICK_EVENT: 3,
  FOREGROUND_ENTER_EVENT: 4,
  FOREGROUND_EXIT_EVENT: 5,
  ABNORMAL_EXIT_EVENT: 6,
  SYSTEM_EXIT_EVENT: 7,
  IMU_DATA_REPORT: 8,
} as const;

export const OsEventTypeName: Record<number, string> = {
  0: "CLICK_EVENT",
  1: "SCROLL_TOP_EVENT",
  2: "SCROLL_BOTTOM_EVENT",
  3: "DOUBLE_CLICK_EVENT",
  4: "FOREGROUND_ENTER_EVENT",
  5: "FOREGROUND_EXIT_EVENT",
  6: "ABNORMAL_EXIT_EVENT",
  7: "SYSTEM_EXIT_EVENT",
  8: "IMU_DATA_REPORT",
};
