const test = require('node:test');
const assert = require('node:assert/strict');
const p = require('../.test-build/app/g2/ble-protocol.js');
const { identifyIosPeripheral, deviceAddressError } = require('../.test-build/app/g2/ios-peripheral-identity.js');
const { GlassesSession } = require('../.test-build/app/g2/glasses-session.js');
const { deflate, inflate } = require('pako');
const hex = bytes => Buffer.from(bytes).toString('hex');
const string = (field, text) => p.bytes(field, new Uint8Array(Buffer.from(text)));

// Generated by compiling the existing Android BleProtocol.java/BmpUtil.java,
// plus BleImageOptimizer's unchanged RLE method, with javac 25.0.2.
test('iOS/shared protocol matches Android-generated wire vectors byte for byte', () => {
  const vectors = [
    [p.authentication(101), '080410651a0408011004'],
    [p.prelude(), '0802109c01220a1a081206120408001000'],
    [p.createLayout(102), '080010661a3808021a1c0800100018c00420a0024801520964617368626f617264580162012022130800100018c00420a002280a3205696d67303028904e'],
    [p.heartbeat(103), '080c106772020800'],
    [p.settingsQuery(104), '0802106822020801'],
    [p.shutdown(105), '080910695a020801'],
    [p.framebufferLease(true), '08011000aa0606464301050000'],
    [p.framebufferLease(false), '08011000aa0606464301060000'],
    [p.imageFragment(106, new Uint8Array([6, 1, 2, 3, 4]), 0), '0803106a2a1a080a1205696d673030180a200528003000380542050601020304'],
    [p.frameMessage(p.authentication(101), 128, 0, 64)[0], 'aa21400c01018000080410651a04080110041024'],
  ];
  for (const [actual, expected] of vectors) assert.equal(hex(actual), expected);
  const packed = p.packGray4(new Uint8Array([0, 1, 7, 8, 15, 16, 23, 24, 127, 128, 247, 255]), 3, 4);
  assert.equal(hex(packed), '0000111012808ff0');
  assert.equal(hex(p.rle4(packed)), '40311011121810182f10');
});

test('negotiated-MTU framing reassembles split and coalesced notifications and rejects bad CRC', () => {
  const payload = p.concat(p.integer(1, 3), p.integer(2, 110), p.bytes(8, new Uint8Array(3900).fill(55)));
  const frames = p.frameMessage(payload, 0xe0, 0x20, 17, 185);
  assert.ok(frames.every(f => f.length <= 185));
  const receiver = new p.MessageReceiver(), stream = p.concat(...frames);
  assert.deepEqual(receiver.receive('L', stream.slice(0, 7)), []);
  const messages = receiver.receive('L', stream.slice(7));
  assert.equal(messages.length, 1); assert.deepEqual(messages[0].payload, payload);
  stream[stream.length - 1] ^= 1;
  assert.deepEqual(receiver.receive('L', stream), []);
  assert.throws(() => p.frameMessage(payload, 1, 0, 1, 10), /too small/);
  assert.throws(() => p.readBytes(new Uint8Array([0x1a, 0x7f]), 3), /Truncated/);
});

test('interleaved links and missing/expired fragments cannot produce false ACKs', () => {
  const payload = p.concat(p.integer(1, 3), p.integer(2, 110), p.bytes(8, new Uint8Array(300)));
  const frames = p.frameMessage(payload, 224, 0, 17), receiver = new p.MessageReceiver();
  assert.deepEqual(receiver.receive('L', frames[0], 0), []);
  assert.deepEqual(receiver.receive('R', frames[1], 1), []);
  assert.deepEqual(receiver.receive('L', frames[1], 6000), []);
  assert.equal(receiver.receive('L', p.concat(...frames), 6001).length, 1);
});

test('full-frame RLE splits 65535-pixel runs and preserves opaque near-black', () => {
  const packed = p.packGray4(new Uint8Array(640 * 480).fill(1), 640, 480);
  assert.ok(packed.every(v => v === 0));
  const encoded = p.rle4(packed);
  let count = 0, offset = 0;
  while (offset < encoded.length) {
    const token = encoded[offset++]; let run = token >>> 4;
    if (!run) { run = encoded[offset++]; if (!run) { run = encoded[offset] | (encoded[offset + 1] << 8); offset += 2; } }
    assert.equal(token & 15, 0); count += run;
  }
  assert.equal(count, 640 * 480);
  assert.deepEqual(inflate(deflate(encoded)), encoded);
});

test('iOS mapping requires the full advertised MAC, never just a name suffix', () => {
  const raw = { identifier: '8A2DD845-B208-F292-EB77-F4645C5AC42F', name: 'Even G2_32_L_B6ECE0',
    manufacturerData: '4552' + Buffer.from('S211GBBC180304').toString('hex') + 'e0ecb61412e001', rssi: -45, connectable: true };
  const device = identifyIosPeripheral(raw);
  assert.equal(device.address, 'E0:12:14:B6:EC:E0'); assert.equal(device.role, 'left');
  assert.equal(device.identifier, raw.identifier); assert.equal(device.serial, 'S211GBBC180304');
  assert.equal(identifyIosPeripheral({ ...raw, manufacturerData: '' }), null);
  assert.equal(identifyIosPeripheral({ ...raw, identifier: 'not-a-uuid' }), null);
  assert.match(deviceAddressError({ left: device.address, right: device.address, ring: '' }), /different/);
  assert.equal(deviceAddressError({ left: device.address, right: 'AA:BB:CC:DD:EE:FF', ring: '' }), null);
});

test('ring and arm input decoders preserve gesture and source', () => {
  assert.equal(p.decodeRingInput(new Uint8Array([255, 4, 2])).eventType, 3);
  assert.equal(p.decodeRingInput(new Uint8Array([255, 5, 0])).eventType, 2);
  assert.equal(p.decodeRingInput(new Uint8Array([255, 5, 2])).eventType, 1);
  assert.equal(p.decodeRingInput(new Uint8Array([0, 9, 97, 0, 8, 0, 0, 0, 0, 0, 0])).eventType, 10);
  assert.equal(p.decodeRingInput(new Uint8Array([255, 4, 99])), null);
  const payload = p.bytes(13, p.bytes(3, p.concat(p.integer(1, 9), p.integer(2, 3))));
  assert.equal(p.decodeGlassesInput({ sid: 224, flag: 1, payload }).eventSource, 3);
  assert.equal(p.decodeGlassesInput({ sid: 224, flag: 32, payload }), null);
});

class FakeTransport {
  events = new Set(); receiver = new p.MessageReceiver(); sent = []; subscriptions = []; closed = [];
  hold = false; held = []; stock = false;
  onEvent(fn) { this.events.add(fn); return () => this.events.delete(fn); }
  emit(event) { for (const fn of [...this.events]) fn(event); }
  async resolveDevices() { return { left: 'L', right: 'R', ring: 'ring' }; }
  async connect(id) { return { characteristics: id === 'ring' ? p.RING_NOTIFY : [p.G2_WRITE, p.G2_NOTIFY], maxWrite: 185 }; }
  async subscribe(id, characteristic) { this.subscriptions.push([id, characteristic]); }
  disconnect(id) { this.closed.push(id); this.emit({ kind: 'disconnected', identifier: id }); }
  stopScan() {}
  ack(id, message, overrides = {}) {
    let body = new Uint8Array();
    if (message.sid === p.SID.auth) body = p.bytes(3, new Uint8Array());
    if (message.sid === p.SID.settings) body = p.concat(p.bytes(4, p.concat(string(5, '2.2.9.22'), string(6, '2.2.9.22'), p.integer(12, 90), p.integer(13, 0))), string(100, this.stock ? '' : 'EVENCFW/18 img640 fbguard wearnotify cleanup11'));
    const responseCommand = message.sid === p.SID.launch ? 1 : message.sid === p.SID.hub && message.command === 0 ? 1 : message.sid === p.SID.hub && message.command === 3 ? 4 : message.command;
    const payload = p.concat(p.integer(1, responseCommand), p.integer(2, overrides.magic ?? message.magic), body);
    const data = hex(p.concat(...p.frameMessage(payload, overrides.sid ?? message.sid, 0, 12)));
    // The right/master link also carries ACKs for image writes to L.
    this.emit({ kind: 'notification', identifier: overrides.identifier ?? 'R', characteristic: p.G2_NOTIFY, data });
  }
  async write(id, characteristic, frame) {
    assert.equal(characteristic, p.G2_WRITE); assert.ok(frame.length <= 185);
    for (const message of this.receiver.receive(id, frame)) {
      this.sent.push({ id, message });
      if (!message.magic) continue;
      if (this.hold) this.held.push({ id, message });
      else queueMicrotask(() => this.ack(id, message));
    }
  }
}
const addresses = { right: 'AA:BB:CC:DD:EE:01', left: 'AA:BB:CC:DD:EE:02', ring: '' };
async function until(predicate) {
  for (let i = 0; i < 100; i++) { if (predicate()) return; await new Promise(resolve => setTimeout(resolve, 5)); }
  assert.fail('Timed out waiting for test state');
}
function harness(t, transport = new FakeTransport()) {
  const states = [], input = [];
  const session = new GlassesSession(transport, deflate, state => states.push(state), event => input.push(event));
  t.after(async () => { transport.hold = false; await session.stop(); });
  return { transport, session, states, input };
}
test('session authenticates both arms, checks firmware and sends acknowledged display data to L', async t => {
  const h = harness(t); await h.session.start({ ...addresses, ring: 'AA:BB:CC:DD:EE:03' });
  assert.equal(h.session.state.phase, 'connected'); assert.equal(h.session.state.ring, true);
  assert.equal(h.session.state.battery, 90);
  assert.equal(h.session.state.charging, false);
  assert.deepEqual(h.transport.sent.filter(s => s.message.sid === 128).map(s => s.id).sort(), ['L', 'R']);
  h.session.setFrame(new Uint8Array(640 * 480)); await until(() => h.session.state.frames === 1);
  const image = h.transport.sent.find(s => s.message.sid === 224 && s.message.command === 3);
  assert.equal(image.id, 'L');
  const fragment = p.readBytes(image.message.payload, 5), payload = p.readBytes(fragment, 8);
  assert.equal(payload[0], 6); assert.ok(inflate(payload.slice(1)).length > 0);
  await h.session.stop();
  assert.equal(h.session.state.phase, 'disconnected');
  assert.ok(h.transport.sent.some(s => s.message.command === 3 && p.readBytes(p.readBytes(s.message.payload, 5), 8)[0] === 11));
});
test('stock firmware is rejected before framebuffer/layout/image commands', async t => {
  const transport = new FakeTransport(); transport.stock = true;
  const h = harness(t, transport); await h.session.start(addresses);
  assert.equal(h.session.state.phase, 'error'); assert.match(h.session.state.status, /modified firmware/);
  assert.ok(!transport.sent.some(s => s.message.sid === p.SID.hub));
});
test('one unavailable R1 notification channel does not discard the usable channel', async t => {
  const transport = new FakeTransport();
  const subscribe = transport.subscribe.bind(transport);
  transport.subscribe = async (id, uuid) => {
    if (uuid === p.RING_NOTIFY[0]) throw new Error('CCCD timed out');
    return subscribe(id, uuid);
  };
  const h = harness(t, transport); await h.session.start({ ...addresses, ring: 'AA:BB:CC:DD:EE:03' });
  assert.equal(h.session.state.ring, true);
  assert.ok(transport.subscriptions.some(([id, uuid]) => id === 'ring' && uuid === p.RING_NOTIFY[1]));
  assert.ok(!transport.closed.includes('ring'));
});
test('disconnect cancels in-flight authentication and ignores late acknowledgements', async t => {
  const h = harness(t); h.transport.hold = true;
  const start = h.session.start(addresses); await until(() => h.transport.held.length === 2);
  await h.session.stop();
  for (const held of h.transport.held) h.transport.ack(held.id, held.message);
  await start;
  assert.equal(h.session.state.phase, 'disconnected');
  assert.ok(!h.states.some(s => s.phase === 'connected'));
  assert.equal(h.transport.sent.length, 2);
});
test('wrong peer, service or magic cannot satisfy a pending request; timeout rejects it', async t => {
  const h = harness(t); await h.session.start(addresses); h.transport.hold = true;
  const request = h.session.request('right', p.SID.hub, p.heartbeat, 'test heartbeat', 30);
  const rejected = assert.rejects(request, /not acknowledged/);
  await until(() => h.transport.held.length > 0);
  const held = h.transport.held[0];
  h.transport.ack(held.id, held.message, { identifier: 'stranger' });
  h.transport.ack(held.id, held.message, { sid: 9 });
  h.transport.ack(held.id, held.message, { magic: held.message.magic + 1 });
  await rejected;
});

test('ring disconnect retries independently and stop cancels further retries', async t => {
  const h = harness(t); await h.session.start({ ...addresses, ring: 'AA:BB:CC:DD:EE:03' });
  const armMessages = h.transport.sent.length;
  h.transport.emit({ kind: 'disconnected', identifier: 'ring', message: 'Link lost' });
  assert.equal(h.session.state.phase, 'connected'); assert.equal(h.session.state.ring, false);
  assert.notEqual(h.session.ringRetryTimer, null);
  await new Promise(resolve => setTimeout(resolve, 2100));
  assert.equal(h.session.state.ring, true);
  assert.equal(h.transport.sent.length, armMessages);
  assert.equal(h.transport.subscriptions.filter(([id]) => id === 'ring').length, 4);
  h.transport.emit({ kind: 'disconnected', identifier: 'ring' });
  await h.session.stop();
  assert.equal(h.session.ringRetryTimer, null);
});

test('a BLE wake services overdue heartbeat and lease without waiting for a suspended poll timer', async t => {
  const h = harness(t); await h.session.start(addresses);
  clearTimeout(h.session.timer); h.session.timer = null;
  h.session.lastHeartbeat = Date.now() - 12_000;
  h.session.lastLease = Date.now() - 60_000;
  const before = h.transport.sent.length;
  const data = hex(p.concat(...p.frameMessage(p.integer(1, 6), p.SID.auth, 1, 22)));
  h.transport.emit({ kind: 'notification', identifier: 'L', characteristic: p.G2_NOTIFY, data });
  // pump starts in the notification callback, before any timers can fire.
  assert.equal(h.session.pumping, true);
  await until(() => !h.session.pumping);
  const sent = h.transport.sent.slice(before);
  assert.equal(sent.filter(s => s.message.sid === p.SID.hub && s.message.command === 12).length, 1);
  assert.deepEqual(sent.filter(s => s.message.sid === p.SID.settings).map(s => s.id).sort(), ['L', 'R']);
  assert.equal(h.session.state.phase, 'connected');
  assert.deepEqual(h.transport.closed, []);
  await h.session.stop();
  const count = h.transport.sent.length;
  h.session.wake();
  h.transport.emit({ kind: 'notification', identifier: 'L', characteristic: p.G2_NOTIFY, data });
  assert.equal(h.transport.sent.length, count);
  assert.equal(h.session.state.phase, 'disconnected');
});

test('glasses mic uses Android wire control and only routes bound-arm audio during capture', async t => {
  assert.equal(hex(p.audioControl(101, true)), '080f10659201020801');
  assert.equal(hex(p.audioControl(101, false)), '080f10659201020800');
  const h = harness(t), audio = [];
  await h.session.start(addresses);
  const send = id => h.transport.emit({ kind: 'notification', identifier: id, characteristic: p.G2_RENDER_NOTIFY, data: '010203' });
  send('R'); assert.equal(audio.length, 0);
  await h.session.setMicrophone(true, bytes => audio.push(hex(bytes)));
  assert.ok(h.transport.subscriptions.some(([id, c]) => id === 'R' && c === p.G2_RENDER_NOTIFY));
  assert.ok(h.transport.subscriptions.some(([id, c]) => id === 'L' && c === p.G2_RENDER_NOTIFY));
  send('stranger'); send('ring'); send('L'); send('R');
  assert.deepEqual(audio, ['010203', '010203']);
  const disabling = h.session.setMicrophone(false);
  send('R'); assert.equal(audio.length, 2); // Immediate, before the disable ACK.
  await disabling;
  assert.deepEqual(h.transport.sent.filter(s => s.message.command === 15).map(s =>
    [s.id, p.readInteger(p.readBytes(s.message.payload, 18), 1)]), [['R', 1], ['R', 0]]);
});
test('release while microphone enable awaits ACK sends disable last and rejects further audio', async t => {
  const h = harness(t); await h.session.start(addresses);
  h.transport.hold = true;
  let packets = 0;
  const enabling = h.session.setMicrophone(true, () => packets++);
  await until(() => h.transport.held.some(s => s.message.command === 15));
  const disabling = h.session.setMicrophone(false);
  h.transport.emit({ kind: 'notification', identifier: 'R', characteristic: p.G2_RENDER_NOTIFY, data: '01' });
  assert.equal(packets, 0);
  h.transport.hold = false;
  for (const s of h.transport.held) h.transport.ack(s.id, s.message);
  await Promise.all([enabling, disabling]);
  const mic = h.transport.sent.filter(s => s.message.command === 15);
  assert.equal(p.readInteger(p.readBytes(mic.at(-1).message.payload, 18), 1), 0);
});

test('iOS traffic counts framed writes and logical messages, and advances fps only after the complete image ACK', async t => {
  const { iosBleTraffic } = require('../.test-build/app/g2/ble-traffic-counters.js');
  const h = harness(t); await h.session.start(addresses);
  const before = iosBleTraffic.sample();
  let writtenBytes = 0;
  const write = h.transport.write.bind(h.transport);
  h.transport.write = async (...args) => { await write(...args); writtenBytes += args[2].length; };
  // Force multiple EvenHub messages so first-message ACK is not mistaken for a frame.
  h.session.deflate = () => new Uint8Array(8000).fill(1);
  h.transport.hold = true;
  h.session.setFrame(new Uint8Array(640 * 480).fill(255));
  await until(() => iosBleTraffic.sample().messages > before.messages);
  assert.equal(iosBleTraffic.sample().frames, before.frames);
  assert.equal(iosBleTraffic.sample().bytes - before.bytes, writtenBytes);
  h.transport.hold = false;
  for (const held of h.transport.held) h.transport.ack(held.id, held.message);
  await until(() => h.session.state.frames === 1);
  const after = iosBleTraffic.sample();
  assert.equal(after.messages - before.messages, 3);
  assert.equal(after.frames - before.frames, 1);
  assert.equal(after.bytes - before.bytes, writtenBytes);
  assert.ok(writtenBytes > 8001); // Includes protobuf, fragmentation headers and CRCs.
  h.session.setFrame(new Uint8Array(640 * 480).fill(255));
  await h.session.pump();
  assert.deepEqual(iosBleTraffic.sample(), after); // Deduplicated image is not an ACKed frame.
  await h.session.stop();
  assert.equal(iosBleTraffic.sample().frames, after.frames); // No reset on disconnect.
});

const imageMessages = transport => transport.sent.filter(s => s.message.sid === p.SID.hub && s.message.command === 3);
const imageBody = sent => p.readBytes(sent.message.payload, 5);
const ack = (transport, sent) => transport.ack(sent.id, sent.message);
const tick = () => new Promise(resolve => setImmediate(resolve));

test('display window sends three complete messages before any ACK and refills on an out-of-order ACK', async t => {
  const h = harness(t); await h.session.start(addresses);
  // Five protocol messages, each split into many negotiated-MTU BLE writes.
  const compressed = Uint8Array.from({ length: 16000 }, (_, i) => i & 255);
  h.session.deflate = () => compressed; h.transport.hold = true;
  h.session.setFrame(new Uint8Array(640 * 480).fill(255));
  await until(() => imageMessages(h.transport).length === 3);
  await tick(); assert.equal(imageMessages(h.transport).length, 3);
  assert.equal(h.session.state.frames, 0);
  const first = imageMessages(h.transport);
  ack(h.transport, first[1]); // Relayed ACKs need not arrive in submission order.
  await until(() => imageMessages(h.transport).length === 4);
  ack(h.transport, first[1]); // Duplicate ACK must not open another slot.
  await tick(); assert.equal(imageMessages(h.transport).length, 4);
  ack(h.transport, first[2]);
  await until(() => imageMessages(h.transport).length === 5);
  const sent = imageMessages(h.transport);
  assert.deepEqual(sent.map(s => p.readInteger(imageBody(s), 6)), [0, 1, 2, 3, 4]);
  assert.deepEqual(p.concat(...sent.map(s => p.readBytes(imageBody(s), 8))), p.concat(new Uint8Array([6]), compressed));
  ack(h.transport, sent[4]); ack(h.transport, sent[3]);
  await tick(); assert.equal(h.session.state.frames, 0); // First fragment still unacknowledged.
  ack(h.transport, sent[0]);
  await until(() => h.session.state.frames === 1);
  assert.equal(h.session.displayInFlight, 0); assert.equal(h.session.displayFrames.length, 0);
});

test('display pipelines across frames, deduplicates against enqueued images and coalesces to the newest waiting frame', async t => {
  const h = harness(t); await h.session.start(addresses); h.transport.hold = true;
  const submit = async value => { h.session.setFrame(new Uint8Array(640 * 480).fill(value)); await h.session.pump(); await tick(); };
  await submit(0); await until(() => imageMessages(h.transport).length === 1);
  await submit(0); assert.equal(imageMessages(h.transport).length, 1); // Duplicate still in flight.
  await submit(255); await submit(0); // A -> B -> A must transmit all three.
  await until(() => imageMessages(h.transport).length === 3);
  const sent = imageMessages(h.transport);
  assert.deepEqual(p.readBytes(imageBody(sent[0]), 8), p.readBytes(imageBody(sent[2]), 8));
  await submit(80); await submit(160); // Only the newest waiting frame survives.
  assert.equal(imageMessages(h.transport).length, 3);
  ack(h.transport, sent[2]); ack(h.transport, sent[1]); await tick();
  assert.equal(h.session.state.frames, 0);
  assert.equal(h.session.displayFrames.length, 3); // Bounded behind the missing oldest ACK.
  assert.equal(imageMessages(h.transport).length, 3);
  ack(h.transport, sent[0]);
  await until(() => imageMessages(h.transport).length === 4);
  assert.equal(h.session.state.frames, 3);
  const newest = imageMessages(h.transport)[3];
  assert.deepEqual(p.readBytes(imageBody(newest), 8), p.concat(new Uint8Array([6]), deflate(p.rle4(p.packGray4(new Uint8Array(640 * 480).fill(160), 640, 480)))));
  ack(h.transport, newest); await until(() => h.session.state.frames === 4);
  await submit(160); assert.equal(imageMessages(h.transport).length, 4);
});

test('ACK timeout starts after transport writes drain; a lost display ACK flushes the whole pipeline', async t => {
  const h = harness(t); await h.session.start(addresses);
  const request = h.session.request.bind(h.session);
  h.session.request = (role, sid, build, label, ...rest) => request(role, sid, build, label, ...(label === 'Display frame' ? [40] : rest));
  const write = h.transport.write.bind(h.transport);
  let release;
  const blocked = new Promise(resolve => { release = resolve; });
  h.transport.write = async (...args) => { if (args[0] === 'L') await blocked; await write(...args); };
  h.transport.hold = true; h.session.deflate = () => new Uint8Array(16000);
  h.session.setFrame(new Uint8Array(640 * 480)); await h.session.pump();
  await new Promise(resolve => setTimeout(resolve, 65));
  assert.equal(h.session.state.phase, 'connected'); assert.equal(imageMessages(h.transport).length, 0);
  release(); await until(() => imageMessages(h.transport).length === 3);
  const stale = imageMessages(h.transport);
  await until(() => h.session.state.phase === 'retrying');
  assert.match(h.session.state.status, /Display frame was not acknowledged/);
  assert.equal(h.session.displayInFlight, 0); assert.equal(h.session.displayFrames.length, 0);
  assert.equal(h.session.lastEnqueued, null); assert.equal(h.session.pending.size, 0);
  for (const sent of stale) ack(h.transport, sent);
  await tick(); assert.equal(h.session.state.frames, 0); assert.equal(imageMessages(h.transport).length, 3);
  // A new session must resend even the identical image; old ACKs cannot count it.
  await h.session.stop(); h.transport.hold = false; await h.session.start(addresses);
  h.session.deflate = deflate; h.transport.hold = true;
  h.session.setFrame(new Uint8Array(640 * 480));
  await until(() => imageMessages(h.transport).length === 4);
  for (const sent of stale) ack(h.transport, sent);
  await tick(); assert.equal(h.session.state.frames, 0);
  ack(h.transport, imageMessages(h.transport)[3]); await until(() => h.session.state.frames === 1);
});

test('failed transport write prevents queued display messages from being written', async t => {
  const h = harness(t); await h.session.start(addresses);
  let attempts = 0;
  const write = h.transport.write.bind(h.transport);
  h.transport.write = async (...args) => {
    if (args[0] === 'L') { attempts++; throw new Error('test write failed'); }
    return write(...args);
  };
  h.session.deflate = () => new Uint8Array(16000);
  h.session.setFrame(new Uint8Array(640 * 480));
  await until(() => h.session.state.phase === 'retrying');
  assert.equal(attempts, 1); assert.equal(h.session.pending.size, 0);
  assert.equal(h.session.displayInFlight, 0); assert.equal(h.session.state.frames, 0);
});

test('disconnect cancels the display window and sends cleanup after the queued images stop', async t => {
  const h = harness(t); await h.session.start(addresses);
  h.transport.hold = true; h.session.deflate = () => new Uint8Array(16000);
  h.session.setFrame(new Uint8Array(640 * 480));
  await until(() => imageMessages(h.transport).length === 3);
  const stale = imageMessages(h.transport);
  h.transport.hold = false; await h.session.stop();
  for (const sent of stale) ack(h.transport, sent);
  await tick();
  assert.equal(h.session.state.phase, 'disconnected'); assert.equal(h.session.state.frames, 0);
  assert.equal(h.session.displayInFlight, 0); assert.equal(h.session.displayFrames.length, 0);
  const images = imageMessages(h.transport);
  assert.equal(images.length, 4); assert.deepEqual(p.readBytes(imageBody(images[3]), 8), new Uint8Array([11]));
});

test('a full display window leaves glasses input, microphone control and audio responsive', async t => {
  const h = harness(t); await h.session.start(addresses);
  h.transport.hold = true; h.session.deflate = () => new Uint8Array(16000);
  h.session.setFrame(new Uint8Array(640 * 480));
  await until(() => imageMessages(h.transport).length === 3);
  const input = p.bytes(13, p.bytes(3, p.concat(p.integer(1, 9), p.integer(2, 3))));
  h.transport.emit({ kind: 'notification', identifier: 'R', characteristic: p.G2_NOTIFY,
    data: hex(p.concat(...p.frameMessage(input, p.SID.hub, 1, 22))) });
  assert.equal(h.input.length, 1); assert.equal(h.input[0].eventSource, 3);
  const audio = [], enabling = h.session.setMicrophone(true, packet => audio.push(hex(packet)));
  await until(() => h.transport.sent.some(s => s.message.command === 15));
  ack(h.transport, h.transport.sent.find(s => s.message.command === 15)); await enabling;
  h.transport.emit({ kind: 'notification', identifier: 'L', characteristic: p.G2_RENDER_NOTIFY, data: '010203' });
  assert.deepEqual(audio, ['010203']);
  assert.equal(imageMessages(h.transport).length, 3); assert.equal(h.session.state.frames, 0);
  assert.equal(h.session.displayInFlight, 3);
});

test('pipelined bounding boxes reconstruct moving and erased content against the last queued frame', async t => {
  const { applyDisplayPayload } = require('./helpers/display-payload.cjs');
  const h = harness(t); await h.session.start(addresses); h.transport.hold = true;
  const base = new Uint8Array(640 * 480), a = base.slice(), b = base.slice();
  a[11 * 640 + 13] = 255; b[11 * 640 + 101] = 160;
  const frames = [base, a, b];
  for (let i = 0; i < frames.length; i++) {
    h.session.setFrame(frames[i]); await h.session.pump();
    await until(() => imageMessages(h.transport).length === i + 1);
  }
  const messages = imageMessages(h.transport), payloads = messages.map(m => p.readBytes(imageBody(m), 8));
  assert.deepEqual(payloads.map(b => b[0]), [6, 3, 3]);
  assert.deepEqual(payloads.slice(1).map(b => b[5] | (b[6] << 8)), [1, 2]);
  assert.equal(h.session.state.frames, 0); // All three updates precede any ACK.
  let shadow = new Uint8Array(320 * 480);
  for (let i = 0; i < payloads.length; i++) {
    shadow = applyDisplayPayload(shadow, payloads[i]);
    assert.deepEqual(shadow, p.packGray4(frames[i], 640, 480));
  }
  // A late ACK for the old full frame must not replace the delta comparison base.
  ack(h.transport, messages[0]); await until(() => h.session.state.frames === 1);
  h.session.setFrame(base); await h.session.pump();
  await until(() => imageMessages(h.transport).length === 4);
  const clear = p.readBytes(imageBody(imageMessages(h.transport)[3]), 8);
  assert.equal(clear[0], 3); assert.equal(clear[1], 25); // Only B's dot needs clearing.
  assert.deepEqual(applyDisplayPayload(shadow, clear), p.packGray4(base, 640, 480));
  for (const message of imageMessages(h.transport).slice(1)) ack(h.transport, message);
  await until(() => h.session.state.frames === 4);
});

test('delta ids skip reserved values and advance only on emitted deltas; reconnect reseeds with a full frame', async t => {
  const h = harness(t); await h.session.start(addresses);
  const submit = async gray => {
    const before = h.session.state.frames; h.session.setFrame(gray);
    await until(() => h.session.state.frames === before + 1);
    return p.readBytes(imageBody(imageMessages(h.transport).at(-1)), 8);
  };
  const base = new Uint8Array(640 * 480), next = base.slice(); next[1234] = 255;
  assert.equal((await submit(base))[0], 6);
  h.session.nextImageFrameId = 0xfffe;
  const delta = await submit(next); assert.equal(delta[5] | (delta[6] << 8), 0xfffe);
  h.session.setFrame(next); await h.session.pump(); await tick();
  assert.equal(h.session.nextImageFrameId, 1);
  const full = await submit(new Uint8Array(640 * 480).fill(255)); assert.equal(full[0], 6);
  assert.equal(h.session.nextImageFrameId, 1);
  const clear = await submit(next); assert.equal(clear[0], 6); // Whole-screen bounding box.
  const wrapped = await submit(base); assert.equal(wrapped[5] | (wrapped[6] << 8), 1);
  await h.session.stop(); await h.session.start(addresses);
  assert.equal((await submit(base))[0], 6); // Even the same pixels need a trusted full base.
});

test('a lost delta ACK invalidates the queued base and late delta ACKs cannot seed a new session', async t => {
  const h = harness(t); await h.session.start(addresses);
  const base = new Uint8Array(640 * 480); h.session.setFrame(base);
  await until(() => h.session.state.frames === 1);
  const request = h.session.request.bind(h.session);
  h.session.request = (role, sid, build, label, ...rest) => request(role, sid, build, label, ...(label === 'Display frame' ? [50] : rest));
  h.transport.hold = true;
  const a = base.slice(), b = base.slice(); a[1234] = 255; b[4321] = 255;
  h.session.setFrame(a); await h.session.pump();
  h.session.setFrame(b); await h.session.pump();
  await until(() => imageMessages(h.transport).length === 3);
  const stale = imageMessages(h.transport).slice(1);
  assert.deepEqual(stale.map(m => p.readBytes(imageBody(m), 8)[0]), [3, 3]);
  ack(h.transport, stale[1]); // Even a later successful delta does not rescue a hole.
  await until(() => h.session.state.phase === 'retrying');
  assert.equal(h.session.lastEnqueued, null); assert.equal(h.session.state.frames, 1);
  await h.session.stop(); h.transport.hold = false; await h.session.start(addresses);
  h.transport.hold = true; h.session.setFrame(b); await h.session.pump();
  await until(() => imageMessages(h.transport).length === 4);
  const reseed = imageMessages(h.transport)[3]; assert.equal(p.readBytes(imageBody(reseed), 8)[0], 6);
  for (const message of stale) ack(h.transport, message);
  await tick(); assert.equal(h.session.state.frames, 1);
  ack(h.transport, reseed); await until(() => h.session.state.frames === 2);
});
